---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.36
  JSON::XS: 0
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Resque
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Fast: 0
  DateTime: 0
  Devel::StackTrace: 0
  JSON: 0
  Redis: 1.904
  Sys::Hostname: 0
  Time::HiRes: 0
version: 0.03
